name: flutter_bloc_practice
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  freezed_annotation: ^2.4.1
  mask_text_input_formatter: ^2.5.0
  pinput: ^3.0.1
  auto_route: ^7.8.4
  flutter_native_splash: ^2.3.4
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  flutter_screenutil: ^5.9.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.3
  auto_route_generator: ^7.3.2
  flutter_launcher_icons: ^0.13.1
  slang_build_runner: ^3.25.0


flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_native_splash:
  background_image: "assets/images/background_splash.png"
  color: "#e1f5fe"

flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "./assets/images/icon.png"
  image_path_android: "./assets/images/icon.png"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"


